-- Mesure : Depenses_Reelles_Par_Annee

CALCULATE(
    SUM(Fact_FinancialAndAccountingManagement[FinancialStatements_ActualExpenses]),
    USERELATIONSHIP(DimDate[PK_Date], Fact_FinancialAndAccountingManagement[FsStatementDateID])
)

