export interface Food {
  food: string | '';
  "Caloric Value": number | 0;
  Fat: number | 0;
  "Saturated Fats": number | 0;
  "Monounsaturated Fats": number | 0;
  "Polyunsaturated Fats": number | 0;
  Carbohydrates: number | 0;
  Sugars: number | 0;
  Protein: number | 0;
  "Dietary Fiber": number | 0;
  Cholesterol: number | 0;
  Sodium: number | 0;
  Water: number | 0;
  "Vitamin A": number | 0;
  "Vitamin B1": number | 0;
  "Vitamin B11": number | 0;
  "Vitamin B12": number | 0;
  "Vitamin B2": number | 0;
  "Vitamin B3": number | 0;
  "Vitamin B5": number | 0;
  "Vitamin B6": number | 0;
  "Vitamin C": number | 0;
  "Vitamin D": number | 0;
  "Vitamin E": number | 0;
  "Vitamin K": number | 0;
  Calcium: number | 0;
  Copper: number | 0;
  Iron: number | 0;
  Magnesium: number | 0;
  Manganese: number | 0;
  Phosphorus: number | 0;
  Potassium: number | 0;
  Selenium: number | 0;
  Zinc: number | 0;
  "Nutrition Density": number | 0;
}
