export interface RecomDetails {
  food: string | null;
  caloric_value: number | null;
  fat: number | null;
  saturated_fats: number | null;
  monounsaturated_fats: number | null;
  polyunsaturated_fats: number | null;
  carbohydrates: number | null;
  sugars: number | null;
  protein: number | null;
  dietary_fiber: number | null;
  cholesterol: number | null;
  sodium: number | null;
  water: number | null;
  vitamin_a: number | null;
  vitamin_b1: number | null;
  vitamin_b11: number | null;
  vitamin_b12: number | null;
  vitamin_b2: number | null;
  vitamin_b3: number | null;
  vitamin_b5: number | null;
  vitamin_b6: number | null;
  vitamin_c: number | null;
  vitamin_d: number | null;
  vitamin_e: number | null;
  vitamin_k: number | null;
  calcium: number | null;
  copper: number | null;
  iron: number | null;
  magnesium: number | null;
  manganese: number | null;
  phosphorus: number | null;
  potassium: number | null;
  selenium: number | null;
  zinc: number | null;
  nutrition_density: number | null;
}

export interface Recom {
  patient: string | null;
  date: string | null;
  recom: RecomDetails[] | [];
}
